title: Title in the config.yml
author: No One
email: wuaf@siafiaf.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome descriptttttttd in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
